Metrics/LineLength:
  Max: 120
Style/FileName:
  Enabled: false
Documentation:
  Enabled: false
AllCops:
  Include:
    - 'app/**/*'
  Excludes:
    - 'db/**'
    - 'config/**'
    - 'script/**'
    - 'db/schema.rb'
    - 'bin/**'
    - 'db/migrate/20180103183643_devise_token_auth_create_users.rb'
  TargetRubyVersion: '2.4'
Style/FrozenStringLiteralComment:
  Enabled: false

